// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateBookGenres implements pgx.CopyFromSource.
type iteratorForCreateBookGenres struct {
	rows                 []CreateBookGenresParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBookGenres) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBookGenres) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookID,
		r.rows[0].GenreID,
	}, nil
}

func (r iteratorForCreateBookGenres) Err() error {
	return nil
}

func (q *Queries) CreateBookGenres(ctx context.Context, arg []CreateBookGenresParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"book_genres"}, []string{"book_id", "genre_id"}, &iteratorForCreateBookGenres{rows: arg})
}
