// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int64       `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Dob       pgtype.Date `json:"dob"`
	Email     string      `json:"email"`
	Gender    string      `json:"gender"`
}

type Book struct {
	BookID          int64          `json:"book_id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	ImageLinks      []string       `json:"image_links"`
	Price           pgtype.Numeric `json:"price"`
	PublicationDate pgtype.Date    `json:"publication_date"`
	AuthorID        int64          `json:"author_id"`
}

type BookGenre struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

type Genre struct {
	GenreID int64  `json:"genre_id"`
	Name    string `json:"name"`
}

type User struct {
	Username          string      `json:"username"`
	HashedPassword    string      `json:"hashed_password"`
	Email             string      `json:"email"`
	Role              pgtype.Text `json:"role"`
	PasswordChangedAt time.Time   `json:"password_changed_at"`
	CreatedAt         time.Time   `json:"created_at"`
}
